/**
* the Model was generated by API Boy
**/
const {Model} = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    class Right extends Model { }
    Right.init({
		name: DataTypes.STRING({length:256})
	}, { sequelize });
    return Right;
};